# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.statusbar = None
        self.menubar = None
        self.status_label = None
        self.id_box = None
        self.candidates_label = None
        self.id_label = None
        self.voting_label = None
        self.submit_button = None
        self.second_button = None
        self.first_button = None
        self.frame = None
        self.centralwidget = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(259, 99, 321, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        self.first_button = QtWidgets.QRadioButton(parent=self.frame)
        self.first_button.setGeometry(QtCore.QRect(120, 160, 100, 20))
        self.first_button.setObjectName("first_button")

        self.second_button = QtWidgets.QRadioButton(parent=self.frame)
        self.second_button.setGeometry(QtCore.QRect(120, 190, 100, 20))
        self.second_button.setObjectName("second_button")

        self.submit_button = QtWidgets.QPushButton(parent=self.frame)
        self.submit_button.setGeometry(QtCore.QRect(90, 240, 131, 32))
        self.submit_button.setObjectName("submit_button")

        self.voting_label = QtWidgets.QLabel(parent=self.frame)
        self.voting_label.setGeometry(QtCore.QRect(110, 40, 81, 21))
        self.voting_label.setObjectName("voting_label")

        self.id_label = QtWidgets.QLabel(parent=self.frame)
        self.id_label.setGeometry(QtCore.QRect(30, 90, 81, 20))
        self.id_label.setObjectName("id_label")

        self.candidates_label = QtWidgets.QLabel(parent=self.frame)
        self.candidates_label.setGeometry(QtCore.QRect(120, 130, 81, 20))
        self.candidates_label.setObjectName("candidates_label")

        self.id_box = QtWidgets.QTextEdit(parent=self.frame)
        self.id_box.setGeometry(QtCore.QRect(110, 90, 131, 21))
        self.id_box.setObjectName("id_box")


        self.status_label = QtWidgets.QLabel(parent=self.frame)
        self.status_label.setGeometry(QtCore.QRect(20, 300, 300, 100))
        self.status_label.setObjectName("status_label")
        self.status_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status_label.setStyleSheet("font-size: 10px; color: red")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting App"))
        self.first_button.setText(_translate("MainWindow", "JAMES"))
        self.second_button.setText(_translate("MainWindow", "ALEXIS"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT"))
        self.voting_label.setText(_translate("MainWindow", "VOTING APP"))
        self.id_label.setText(_translate("MainWindow", "ID NUMBER"))
        self.candidates_label.setText(_translate("MainWindow", "CANDIDATES"))
        self.status_label.setText(_translate("MainWindow", ""))







